version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=studentdb

    ports:
      - "3307:3306"
  springboot-docker-container:
    depends_on:
      - mysqldb
    build: 
      context: ./batch-job/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
        spring.datasource.url  : "spring.datasource.url=jdbc:mysql://localhost:3306/studentdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
        spring.datasource.username : "root"
        spring.datasource.password : "password"
        spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.MySQL5Dialect"
        spring.jpa.hibernate.ddl-auto : "create-drop"
      
    volumes:
       - .m2:/root/.m2